INSERT INTO dictionary(english, french, italian, german, category) VALUES
('red', 'rouge', 'rosso', 'rot', 'colors'),
('blue', 'bleu', 'blu', 'blau', 'colors'),
('green', 'vert', 'verde', 'grün', 'colors'),
('yellow', 'jaune', 'giallo', 'gelb', 'colors'),
('orange', 'orange', 'arancione', 'orange', 'colors'),
('pink', 'rose', 'rosa', 'rosa', 'colors'),
('purple', 'violet', 'viola', 'lila', 'colors'),
('brown', 'marron', 'marrone', 'braun', 'colors'),
('white', 'blanc', 'bianco', 'weiß', 'colors'),
('gray', 'gris', 'grigio', 'grau', 'colors'),
('black', 'noir', 'nero', 'schwarz', 'colors'),
('dog', 'le chien', 'il cane', 'der Hund', 'animals'),
('cat', 'le chat', 'il gatto', 'die Katze', 'animals'),
('rabbit', 'le lapin', 'il coniglio', 'das Kaninchen', 'animals'),
('hamster', 'le hamster', 'il criceto', 'der Hamster', 'animals'),
('goldfish', 'le poisson rouge', 'il pesce rosso', 'der Goldfisch', 'animals'),
('cow', 'la vache', 'la mucca', 'die Kuh', 'animals'),
('sheep', 'le mouton', 'la pecora', 'das Schaf', 'animals'),
('pig', 'le cochon', 'il maiale', 'das Schwein', 'animals'),
('horse', 'le cheval', 'il cavallo', 'das Pferd', 'animals'),
('chicken', 'le poulet', 'il pollo', 'das Huhn', 'animals'),
('fox', 'le renard', 'la volpe', 'der Fuchs', 'animals'),
('deer', 'le cerf', 'il cervo', 'das Reh', 'animals'),
('mouse', 'la souris', 'il topo', 'die Maus', 'animals'),
('rat', 'le rat', 'il ratto', 'die Ratte', 'animals'),
('frog', 'la grenouille', 'la rana', 'der Frosch', 'animals'),
('snake', 'le serpent', 'il serpente', 'die Schlange', 'animals'),
('lion', 'le lion', 'il leone', 'der Löwe', 'animals'),
('tiger', 'le tigre', 'la tigre', 'der Tiger', 'animals'),
('monkey', 'le singe', 'la scimmia', 'der Affe', 'animals'),
('elephant', 'l''éléphant', 'l''elefante', 'der Elefant', 'animals'),
('giraffe', 'la girafe', 'la giraffa', 'die Giraffe', 'animals'),
('bear', 'l''ours', 'l''orso', 'der Bär', 'animals'),
('spider', 'l''araignée', 'il ragno', 'die Spinne', 'animals'),
('bee', 'l''abeille', 'l''ape', 'die Biene', 'animals'),
('butterfly', 'le papillon', 'la farfalla', 'der Schmetterling', 'animals'),
('shark', 'le requin', 'lo squalo', 'der Hai', 'animals'),
('soup', 'la soupe', 'la zuppa', 'die Suppe', 'food'),
('ice cream', 'la glace', 'il gelato', 'das Eis', 'food'),
('butter', 'le beurre', 'il burro', 'die Butter', 'food'),
('cream', 'la crème', 'la panna', 'die Sahne', 'food'),
('cheese', 'le fromage', 'il formaggio', 'der Käse', 'food'),
('eggs', 'les œufs', 'le uova', 'die Eier', 'food'),
('milk', 'le lait', 'il latte', 'die Milch', 'food'),
('yoghurt', 'le yaourt', 'lo yogurt', 'der Joghurt', 'food'),
('bread', 'le pain', 'il pane', 'das Brot', 'food'),
('cake', 'le gâteau', 'la torta', 'der Kuchen', 'food'),
('sugar', 'le sucre', 'lo zucchero', 'der Zucker', 'food'),
('salt', 'le sel', 'il sale', 'das Salz', 'food'),
('pepper', 'le poivre', 'il pepe', 'der Pfeffer', 'food'),
('honey', 'le miel', 'il miele', 'der Honig', 'food'),
('pizza', 'la pizza', 'la pizza', 'die Pizza', 'food'),
('rice', 'le riz', 'il riso', 'der Reis', 'food'),
('spaghetti', 'les spaghettis', 'gli spaghetti', 'die Spaghetti', 'food'),
('chocolate', 'le chocolat', 'il cioccolato', 'die Schokolade', 'food'),
('fish', 'le poisson', 'il pesce', 'der Fisch', 'food'),
('salad', 'la salade', 'l''insalata', 'der Salat', 'food'),
('popcorn', 'le popcorn', 'il popcorn', 'das Popcorn', 'food'),
('meat', 'la viande', 'la carne', 'das Fleisch', 'food'),
('cookies', 'les biscuits', 'i biscotti', 'die Kekse', 'food'),
('fruits', 'les fruits', 'la frutta', 'die Früchte', 'food'),
('vegetables', 'les légumes', 'le verdure', 'das Gemüse', 'food'),
('sandwich', 'le sandwich', 'il panino', 'das Sandwich', 'food');
