INSERT INTO dictionary(english, french, italian, german, category) VALUES
('red', 'rouge', 'rosso', 'rot', 'colors'),
('blue', 'bleu', 'blu', 'blau', 'colors'),
('green', 'vert', 'verde', 'grün', 'colors'),
('yellow', 'jaune', 'giallo', 'gelb', 'colors'),
('orange', 'orange', 'arancione', 'orange', 'colors'),
('pink', 'rose', 'rosa', 'rosa', 'colors'),
('purple', 'violet', 'viola', 'lila', 'colors'),
('brown', 'marron', 'marrone', 'braun', 'colors'),
('white', 'blanc', 'bianco', 'weiß', 'colors'),
('gray', 'gris', 'grigio', 'grau', 'colors'),
('black', 'noir', 'nero', 'schwarz', 'colors'),
('dog', 'le chien', 'il cane', 'der Hund', 'animals'),
('cat', 'le chat', 'il gatto', 'die Katze', 'animals'),
('rabbit', 'le lapin', 'il coniglio', 'das Kaninchen', 'animals'),
('hamster', 'le hamster', 'il criceto', 'der Hamster', 'animals'),
('goldfish', 'le poisson rouge', 'il pesce rosso', 'der Goldfisch', 'animals'),
('cow', 'la vache', 'la mucca', 'die Kuh', 'animals'),
('sheep', 'le mouton', 'la pecora', 'das Schaf', 'animals'),
('pig', 'le cochon', 'il maiale', 'das Schwein', 'animals'),
('horse', 'le cheval', 'il cavallo', 'das Pferd', 'animals'),
('chicken', 'le poulet', 'il pollo', 'das Huhn', 'animals'),
('fox', 'le renard', 'la volpe', 'der Fuchs', 'animals'),
('deer', 'le cerf', 'il cervo', 'das Reh', 'animals'),
('mouse', 'la souris', 'il topo', 'die Maus', 'animals'),
('rat', 'le rat', 'il ratto', 'die Ratte', 'animals'),
('frog', 'la grenouille', 'la rana', 'der Frosch', 'animals'),
('snake', 'le serpent', 'il serpente', 'die Schlange', 'animals'),
('lion', 'le lion', 'il leone', 'der Löwe', 'animals'),
('tiger', 'le tigre', 'la tigre', 'der Tiger', 'animals'),
('monkey', 'le singe', 'la scimmia', 'der Affe', 'animals'),
('elephant', 'l''éléphant', 'l''elefante', 'der Elefant', 'animals'),
('giraffe', 'la girafe', 'la giraffa', 'die Giraffe', 'animals'),
('bear', 'l''ours', 'l''orso', 'der Bär', 'animals'),
('spider', 'l''araignée', 'il ragno', 'die Spinne', 'animals'),
('bee', 'l''abeille', 'l''ape', 'die Biene', 'animals'),
('butterfly', 'le papillon', 'la farfalla', 'der Schmetterling', 'animals'),
('shark', 'le requin', 'lo squalo', 'der Hai', 'animals');
